export const SEARCH_COMPANY_SUCCESS = "SEARCH_COMPANY_SUCCESS";
export const SEARCH_COMPANY_ERROR = "SEARCH_COMPANY_ERROR";

export const SEARCH_CHART_SUCCESS = "SEARCH_CHART_SUCCESS";
export const SEARCH_CHART_ERROR = "SEARCH_CHART_ERROR";
